### ISSUE TITLE
Implement isSpendable function into processor wallet interface.

### ISSUE THREAD

**Issue by TheArchitect108** [serai-dex/serai#129]
The scheduler needs to be able to check the spendability of scheduled transactions and react accordingly.

**Comment by kayabaNerve** [comment]
Short: Will write the relevant code shortly.

Long: The scheduler doesn't "need" to and shouldn't.

When we have transactions exceeding our immediate capacity, we need to schedule a tree of outputs. When we have a child in this tree, it's ability to be created requires the spendability of the parent. This *should* happen via an event that the parent is confirmed.

It's not possible, for an arbitrary coin, to poll for the spendability of an output. While we can create a layer offering sufficient functionality, as will be done here, we can't detect if an output was spent or not. Accordingly, we actually will be defining a function `is_confirmed`. The inefficiency is that instead of waiting to be told, we're regularly asking, when it's more than feasible to just wait to be told.
