### ISSUE TITLE
 Bitcoin Cash (BCH) integration considerations

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#176]
This is solely a tracking issue for notes on the potential of integrating Bitcoin Cash.

Bitcoin Cash is currently in the top 30 and has a strong community.

Bitcoin Cash has diverged from Bitcoin in very notable ways for us. While the bitcoin-rs lib may still be directly usable, they have a 33-byte Schnorr scheme compared to Bitcoin's 32-byte Schnorr scheme, requiring re-implementation of that section.

**Comment by A60AB5450353F40E** [comment]
As you already know from our past interactions, we don't need to rely on multisig or MuSig to commit to BCH funds flow, because we can directly enforce them using Script covenants.

- The contract is here: https://bitcoincashresearch.org/t/monero-bch-atomic-swaps/545/41
- The PoC in Rust by PHCitizen is here: https://bitcoincashresearch.org/t/monero-bch-atomic-swaps/545/40
- mainnet-pat is working on a DEX, some updates here: https://bitcoincashresearch.org/t/monero-bch-atomic-swaps/545/42

**Comment by kayabaNerve** [comment]
Sorry, yet to entirely use covenants would require a light client proof and/or ZK rollup of the Serai chain which effectively makes it a multisig of the Serai validators (not the would-be Serai validators for BCH. The Serai validators for Serai).

Covenants are usable to reduce the amount of signatures required though, as elsewhere noted for Bitcoin.

Please note your linked work on DEX(s) are both fundamentally distinct as they're using atomic swaps. Serai uses over-collateralized multisigs to remove the liveness requirement, offer better UX, and make providing liquidity possible without personally continually running software.

**Comment by kayabaNerve** [comment]
Deprecating this issue from lack of use over the past two years/having Discord channels for this topic.
