### ISSUE TITLE
Providing a better test functionality

### ISSUE THREAD

**Issue by vrx00** [serai-dex/serai#216]
Testing and implementing new methods (like taproot), it would be beneficial to have a test method that allows us to create keys from fixed seeds (instead of generating randomly) or directly create keys from string. It will allow us to verify each step of the implementation (of new methods). i.e. sighash of the input, signature etc. There are many test-vectors out there to help similar test implementation for a new method. It would help us, having a way to utilize this test-vectors for implementing somethings new.

Example:
https://github.com/bitcoin/bips/blob/master/bip-0341/wallet-test-vectors.json

**Comment by kayabaNerve** [comment]
This issue is missing a lot of context.

If this is about the test helper dkg provides, key_gen, it can be run with a seeded RNG trivially. 
`frost::tests::key_gen::<_, C::Curve>(&mut OsRng);`
`frost::tests::key_gen::<_, C::Curve>(&mut Chacha20Rng::from_seed(seed));`
where seed is a `[u8; 32]`.

With regards to creating keys from strings, if you're referring to the cited wallet tests vectors,  those can't be used with `ThresholdKeys` because they're not threshold keys. They're keys. We'd need to implement a dealer key gen which would allow user-provided secrets to be transformed into threshold keys. I'll caveat we should not expose a string interface for that because we cannot properly do so.

I'll finally note you can still apply those vectors to your own code. You just have to apply them to the specific functions they're intended to test for. None of those are intended to test anything regarding threshold multisig, so none of them are directly usable with threshold multisig. Instead, they're about deriving a tweak for a Taproot output, combining it with the key, and generating an address for it. This would be usable by the Rust bitcoin lib/usable to verify your usage of it.

Would you mind clarifying the exact feature you want and its relevancy to the provided test vectors?

**Comment by kayabaNerve** [comment]
De-tagged to just feature as this is a feature request. I'm just unsure for what library it's a feature request/what exactly the feature it is. It sounds like it's a feature request for dealer key gen, though I'm unsure if that legitimately helps you for what you want to do. I'd also point to #199. The `/crypto` folder is currently frozen, so we can't implement that at this time. If this for a feature regarding cryptography, I'll add the crypto label.

**Comment by kayabaNerve** [comment]
*Some of those vectors do cover the message hash, which could be used to test `BitcoinHram`, and the fully signed transaction. I'd like to point out we would never be able to match their signatures/fully signed transaction because FROST will not let you create a specific signature. We could only create a signature over the same message, which is equally valid and a property derived from using the Schnorr algorithm with a correct HRAm (which should be testable, as an isolate, from that vector file if I'm reading it correctly).

**Comment by vrx00** [comment]
`frost::tests::key_gen::<_, C::Curve>(&mut Chacha20Rng::from_seed(seed));` would be enough in my case.
